/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVoicesRouteImport } from './routes/_authenticated/voices'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ApiStreamTranscribeRouteImport } from './routes/api/stream.transcribe'
import { Route as ApiStreamSynthRouteImport } from './routes/api/stream.synth'
import { Route as AuthenticatedVoicesNewRouteImport } from './routes/_authenticated/voices.new'
import { Route as AuthenticatedVoicesIdRouteImport } from './routes/_authenticated/voices.$id'
import { Route as AuthenticatedStudioVoicesRouteImport } from './routes/_authenticated/studio_.voices'
import { Route as ApiPublicBridgeStreamRouteImport } from './routes/api/public/bridge/stream'
import { Route as AuthenticatedStudioVoicesIdRouteImport } from './routes/_authenticated/studio_.voices.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoicesRoute = AuthenticatedVoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiStreamTranscribeRoute = ApiStreamTranscribeRouteImport.update({
  id: '/api/stream/transcribe',
  path: '/api/stream/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamSynthRoute = ApiStreamSynthRouteImport.update({
  id: '/api/stream/synth',
  path: '/api/stream/synth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoicesNewRoute = AuthenticatedVoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedVoicesRoute,
} as any)
const AuthenticatedVoicesIdRoute = AuthenticatedVoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedVoicesRoute,
} as any)
const AuthenticatedStudioVoicesRoute =
  AuthenticatedStudioVoicesRouteImport.update({
    id: '/studio_/voices',
    path: '/studio/voices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBridgeStreamRoute = ApiPublicBridgeStreamRouteImport.update({
  id: '/api/public/bridge/stream',
  path: '/api/public/bridge/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioVoicesIdRoute =
  AuthenticatedStudioVoicesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedStudioVoicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/voices': typeof AuthenticatedVoicesRouteWithChildren
  '/studio/voices': typeof AuthenticatedStudioVoicesRouteWithChildren
  '/voices/$id': typeof AuthenticatedVoicesIdRoute
  '/voices/new': typeof AuthenticatedVoicesNewRoute
  '/api/stream/synth': typeof ApiStreamSynthRoute
  '/api/stream/transcribe': typeof ApiStreamTranscribeRoute
  '/studio/voices/$id': typeof AuthenticatedStudioVoicesIdRoute
  '/api/public/bridge/stream': typeof ApiPublicBridgeStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/voices': typeof AuthenticatedVoicesRouteWithChildren
  '/studio/voices': typeof AuthenticatedStudioVoicesRouteWithChildren
  '/voices/$id': typeof AuthenticatedVoicesIdRoute
  '/voices/new': typeof AuthenticatedVoicesNewRoute
  '/api/stream/synth': typeof ApiStreamSynthRoute
  '/api/stream/transcribe': typeof ApiStreamTranscribeRoute
  '/studio/voices/$id': typeof AuthenticatedStudioVoicesIdRoute
  '/api/public/bridge/stream': typeof ApiPublicBridgeStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/voices': typeof AuthenticatedVoicesRouteWithChildren
  '/_authenticated/studio_/voices': typeof AuthenticatedStudioVoicesRouteWithChildren
  '/_authenticated/voices/$id': typeof AuthenticatedVoicesIdRoute
  '/_authenticated/voices/new': typeof AuthenticatedVoicesNewRoute
  '/api/stream/synth': typeof ApiStreamSynthRoute
  '/api/stream/transcribe': typeof ApiStreamTranscribeRoute
  '/_authenticated/studio_/voices/$id': typeof AuthenticatedStudioVoicesIdRoute
  '/api/public/bridge/stream': typeof ApiPublicBridgeStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profile'
    | '/settings'
    | '/studio'
    | '/voices'
    | '/studio/voices'
    | '/voices/$id'
    | '/voices/new'
    | '/api/stream/synth'
    | '/api/stream/transcribe'
    | '/studio/voices/$id'
    | '/api/public/bridge/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profile'
    | '/settings'
    | '/studio'
    | '/voices'
    | '/studio/voices'
    | '/voices/$id'
    | '/voices/new'
    | '/api/stream/synth'
    | '/api/stream/transcribe'
    | '/studio/voices/$id'
    | '/api/public/bridge/stream'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/studio'
    | '/_authenticated/voices'
    | '/_authenticated/studio_/voices'
    | '/_authenticated/voices/$id'
    | '/_authenticated/voices/new'
    | '/api/stream/synth'
    | '/api/stream/transcribe'
    | '/_authenticated/studio_/voices/$id'
    | '/api/public/bridge/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiStreamSynthRoute: typeof ApiStreamSynthRoute
  ApiStreamTranscribeRoute: typeof ApiStreamTranscribeRoute
  ApiPublicBridgeStreamRoute: typeof ApiPublicBridgeStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voices': {
      id: '/_authenticated/voices'
      path: '/voices'
      fullPath: '/voices'
      preLoaderRoute: typeof AuthenticatedVoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/stream/transcribe': {
      id: '/api/stream/transcribe'
      path: '/api/stream/transcribe'
      fullPath: '/api/stream/transcribe'
      preLoaderRoute: typeof ApiStreamTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/synth': {
      id: '/api/stream/synth'
      path: '/api/stream/synth'
      fullPath: '/api/stream/synth'
      preLoaderRoute: typeof ApiStreamSynthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voices/new': {
      id: '/_authenticated/voices/new'
      path: '/new'
      fullPath: '/voices/new'
      preLoaderRoute: typeof AuthenticatedVoicesNewRouteImport
      parentRoute: typeof AuthenticatedVoicesRoute
    }
    '/_authenticated/voices/$id': {
      id: '/_authenticated/voices/$id'
      path: '/$id'
      fullPath: '/voices/$id'
      preLoaderRoute: typeof AuthenticatedVoicesIdRouteImport
      parentRoute: typeof AuthenticatedVoicesRoute
    }
    '/_authenticated/studio_/voices': {
      id: '/_authenticated/studio_/voices'
      path: '/studio/voices'
      fullPath: '/studio/voices'
      preLoaderRoute: typeof AuthenticatedStudioVoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bridge/stream': {
      id: '/api/public/bridge/stream'
      path: '/api/public/bridge/stream'
      fullPath: '/api/public/bridge/stream'
      preLoaderRoute: typeof ApiPublicBridgeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio_/voices/$id': {
      id: '/_authenticated/studio_/voices/$id'
      path: '/$id'
      fullPath: '/studio/voices/$id'
      preLoaderRoute: typeof AuthenticatedStudioVoicesIdRouteImport
      parentRoute: typeof AuthenticatedStudioVoicesRoute
    }
  }
}

interface AuthenticatedVoicesRouteChildren {
  AuthenticatedVoicesIdRoute: typeof AuthenticatedVoicesIdRoute
  AuthenticatedVoicesNewRoute: typeof AuthenticatedVoicesNewRoute
}

const AuthenticatedVoicesRouteChildren: AuthenticatedVoicesRouteChildren = {
  AuthenticatedVoicesIdRoute: AuthenticatedVoicesIdRoute,
  AuthenticatedVoicesNewRoute: AuthenticatedVoicesNewRoute,
}

const AuthenticatedVoicesRouteWithChildren =
  AuthenticatedVoicesRoute._addFileChildren(AuthenticatedVoicesRouteChildren)

interface AuthenticatedStudioVoicesRouteChildren {
  AuthenticatedStudioVoicesIdRoute: typeof AuthenticatedStudioVoicesIdRoute
}

const AuthenticatedStudioVoicesRouteChildren: AuthenticatedStudioVoicesRouteChildren =
  {
    AuthenticatedStudioVoicesIdRoute: AuthenticatedStudioVoicesIdRoute,
  }

const AuthenticatedStudioVoicesRouteWithChildren =
  AuthenticatedStudioVoicesRoute._addFileChildren(
    AuthenticatedStudioVoicesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedVoicesRoute: typeof AuthenticatedVoicesRouteWithChildren
  AuthenticatedStudioVoicesRoute: typeof AuthenticatedStudioVoicesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedVoicesRoute: AuthenticatedVoicesRouteWithChildren,
  AuthenticatedStudioVoicesRoute: AuthenticatedStudioVoicesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiStreamSynthRoute: ApiStreamSynthRoute,
  ApiStreamTranscribeRoute: ApiStreamTranscribeRoute,
  ApiPublicBridgeStreamRoute: ApiPublicBridgeStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
