// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqoxlasfkjdoipygezog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xb3hsYXNma2pkb2lweWdlem9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyMzI1MjMsImV4cCI6MjA5NzgwODUyM30.LC9dvO5_6mM8Gs4TMrDAH3YBpmGUajtB1Bu5CSVrIdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});